package com.kj.stackchan.voiceaction;

public enum VoiceActionType {
    CREATE_REMINDER,
    SNOOZE_NEXT_REMINDER,
    SKIP_NEXT_REMINDER,
    SET_TEMPORARY_DND,
    SET_VOLUME,
    CREATE_MEMORY_SUGGESTION,
    SWITCH_ROLE,
    ACKNOWLEDGE_NOTIFICATION,
    SNOOZE_NOTIFICATION,
    COMPLETE_NOTIFICATION,
    START_WORKDAY,
    END_WORKDAY,
    START_WORKDAY_REST,
    SNOOZE_WORKDAY_REST,
    SKIP_WORKDAY_REST_FOR_DAY
}
