ALTER TABLE devices
    ADD COLUMN body_motion_supported BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN body_touch_supported BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN proximity_supported BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN ambient_light_supported BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN servo_feedback_supported BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN body_calibrated BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN body_present BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN body_ambient_light VARCHAR(16) NOT NULL DEFAULT 'UNAVAILABLE',
    ADD COLUMN body_motion_state VARCHAR(16) NOT NULL DEFAULT 'DISABLED',
    ADD COLUMN body_last_failure_code VARCHAR(32) NOT NULL DEFAULT 'NONE',
    ADD COLUMN body_failure_count BIGINT NOT NULL DEFAULT 0;
